### PR TITLE
fix(amazon-ca): update selector 

### PR DESCRIPTION
**Pull request by wofnull**
### Description
for maxprice changed for the whole store

Fixes issue #1846 

### Testing

Local Testing done and verified via CA VPN:

image

### CODE REVIEW

**Review by jef — APPROVED** [review]
Great! Thanks @wofnull 😁

**Comment by augustynr** [comment]
I am afraid this patch breaks the code, this is the log from a clean install:
[11:32:26 a.m.] info :: ℹ selected stores: amazon-ca
[11:32:26 a.m.] info :: ℹ selected series: 3060ti, 3080
[11:32:26 a.m.] info :: ✔ sound player found: aplay
[11:33:40 a.m.] info :: ✖ [amazon-ca] [msi (3080)] gaming x trio :: OUT OF STOCK
[11:33:47 a.m.] error :: ✖ [amazon-ca] msi 3080 ventus 3x oc - Cannot read property 'join' of null
[11:33:54 a.m.] error :: ✖ [amazon-ca] evga 3080 ftw3 - Cannot read property 'join' of null

**Comment by wofnull** [comment]
I had the patch up and running for about an hour via VPN before posting this here. There were no errors while testing this.

**Comment by MrRobot245** [comment]
I can confirm, getting the same errors for some amazon-ca 3080s -  Cannot read property 'join' of null

**Pull request merged**
