### PR TITLE
fix(newegg): dedupe nitro+ models

### LINKED ISSUE #1230: RX6800XT Stock on Newegg Generates Alert When Priced over MAX_PRICE_SERIES_RX6800XT Parameter
## Expected Behavior

I should only receive and alert if the RX6800XT is BELOW the max price set in my .env file.

## Current Behavior

A Sapphire RX6800XT Nitro+ card on Newegg is generating an alert at $1,099.67 when my MAX_PRICE_SERIES_RX6800XT parameter is set to 800

## Steps to Reproduce

1.Set variables with max RX6800XT Price at $800 and include Newegg as an included store
2. Run bot
3. Receive Alert to add to cart: https://secure.newegg.com/Shopping/AddtoCart.aspx?Submit=ADD&ItemList=N82E16814202391
4. Add to cart link fails, but page shows card with price above limit: https://www.newegg.com/sapphire-radeon-rx-6800-xt-11304-02-20g/p/N82E16814202391

## Environment

**OS:**
**.env file:**

```
MAX_PRICE_SERIES_3060TI="501"
MAX_PRICE_SERIES_3070="600"
MAX_PRICE_SERIES_3080="850"
MAX_PRICE_SERIES_RX6800XT="800"
MAX_PRICE_SERIES_RX6800="800"
MAX_PRICE_SERIES_SONYPS5C="500"
MAX_PRICE_SERIES_SONYPS5DE="400"
SHOW_ONLY_SERIES="rx6800xt,3060ti,3070,3080,sonyps5c,sonyps5de"
STORES="amazon,bestbuy,walmart,target,newegg"
DESKTOP_NOTIFICATIONS="true"
```

### PR DESCRIPTION
**Pull request by moiLegacy**
### Description

Fixes #1230 
There were two Nitro+ models for newegg with same brand/model/series
Added a a new model type and updated the second Nitro+ in newegg
### Testing
nada

### CODE REVIEW

**Comment by moiLegacy** [comment]
If your test is successful - similar approach might fix 1294 as well.  I see for Amazon the same brand, model, series ....longer term fix might be to strip product number and include that in the max price check so that it doesn't just hit the first brand/model/series it finds in the dictionary/array

**Review by jef — COMMENTED** [review]
Do you mind changing to `nitro+ se`? Otherwise, looks great! Thank you :smile:

**Comment by moiLegacy** [comment]
updated as requested

**Review by jef — APPROVED** [review]
Looks great! Thank you :smile:

**Pull request merged**
