### PR TITLE
feat: add amazon-fr to stores.

### PR DESCRIPTION
**Pull request by Zyde22**
feat: added amazon-fr to stores

### Description
Permit the software to deal with amazon.fr

### CODE REVIEW

**Comment by Zyde22** [comment]
don't talk about `cba68ba` please 😅

**Comment by jef** [comment]
Oh, I see. You reopened 😄

**Comment by Zyde22** [comment]
Yeah first time I do a pull request mb

**Comment by jef** [comment]
Thank you very much! Do you mind updating the `README` to include the new store?

**Comment by Zyde22** [comment]
Done 😊

**Review by jef — APPROVED** [review]
Awesome! Thank you!

**Pull request merged**
