### PR TITLE
feat(api): add GQL subscription API for lookup results

### PR DESCRIPTION
**Pull request by thetimothyp**
### Description
Does not fix an open issue, as I'm not sure if you want this kind of functionality in your code base or if I should just keep it to my fork.

Motivation is to have a GQL feed that can be queried for integration into a more user-friendly UI.

### Testing
- GRAPHQL_PORT env var is defined; expected result is GQL server gets spun up
- No GRAPHQL_PORT env var defined; expected result is no GQL server gets spun up

### New dependencies
[graphql-yoga](https://github.com/prisma-labs/graphql-yoga)

streetmerchant_gql

### CODE REVIEW

**Comment by jef** [comment]
Haha, this is actually pretty cool. Did you make this for a front end?

**Comment by thetimothyp** [comment]
> Haha, this is actually pretty cool. Did you make this for a front end?

Yep, I'm working on a separate frontend which is a WIP atm, but I can only do so much frontend work until I need to switch things up and spend some time on the server side.

**Comment by jef** [comment]
I'm doing quite a bit of work around config and interfaces right now and I really want this in. I haven't forgot about this and will be asking more questions in the near future.

Thank you!

**Comment by jef** [comment]
Removing stale label. Sorry this hasn't gone in. A bit has changed, but not by much. Would like to see this come in the future.

Don't feel a need to update this. I can revisit when we get this point.

Thanks!

**Comment by jef** [comment]
I still want this at some point. Just need to find time to resolve and get it aligned.

**Pull request closed without merging**
