### PR TITLE
feat: bring back ascii banner, but make it configurable

### PR DESCRIPTION
**Pull request by njgreb**
### Description

Fixes the removal of the amazing ascii art with project name change.

### Testing

Run it, toggle the env var ASCII_BANNER to see the different options.

### CODE REVIEW

**Comment by jef** [comment]
Haha, you miss it?

**Comment by njgreb** [comment]
I don't miss it anymore...BECAUSE I PUT IT BACK :)

**Comment by jef** [comment]
Let me think about it 😆 I think we can have this go in, but maybe we can talk about the ASCII art. This one in particular is pretty big. What do you think?

**Comment by njgreb** [comment]
Yeah, this particular font is a bit big...could easily go with a font like the original had:
https://patorjk.com/software/taag/#p=display&f=Big%20Money-se&t=STREET-%20MERCHANT

**Comment by jef** [comment]
I think I prefer hyphen-less, no space. I thought about using '[Bloody](https://patorjk.com/software/taag/#p=display&f=Bloody&t=STREETMERCHANT)' then I went to the full-width text.

**Comment by njgreb** [comment]
If we go with Bloody I am adding the option to pick the font color!

**Comment by jef** [comment]
Haha, I love it. Thanks for the back and forth on this. I didn't want to dictate what font we choose here, but here we are.

> If we go with Bloody I am adding the option to pick the font color!

Talking about customization... https://www.npmjs.com/package/figlet this doesn't have _any_ dependencies. Could be fun to bring this in. What do you think?

**Comment by njgreb** [comment]
You read my mind.  Was just looking at a few ASCII art renderers.  Will probably play with it separate from this over the weekend.

**Comment by jef** [comment]
That being said, I suppose we can pull this in and you can make another PR if you'd like. What would you like to do?

**Comment by njgreb** [comment]
I think merge this and then we continue a larger talk about the state of the frontend else where.

**Pull request merged**
