### PR TITLE
feat(notification): add support for Free mobile

### PR DESCRIPTION
**Pull request by aradenac**
### Description
Allow a user of Free mobile (french carrier) to receive SMS notifications.

The existing sms notification service could not be used, as the Free mobile notification service API does not
require a phone number. Hence PHONE_NUMBER is irrelevant in this context and two dotenv vars have been created.

### Testing
Tryed it with my own Free account, running 

> $ npm run test:notification

### CODE REVIEW

**Comment by jef** [comment]
Interesting. So from what I understand, this mobile company doesn't require you to have a phone number, but a user can still receive SMS?

Strange... But OK!

**Review by jef — APPROVED** [review]
Great! Well thanks for the addition :)

**Comment by aradenac** [comment]
> Interesting. So from what I understand, this mobile company doesn't require you to have a phone number, but a user can still receive SMS?
> 
> Strange... But OK!

Exactly, their web API takes a user ID and a on-purpose generated key only for the SMS notifications service... Like nobody else I guess. Free is often different than the others carriers (e.g. they where the first allowing users having a static public IP for home server at no cost). Provided their "home-automation" services come with no additional charges, they are often a good choice for hobbyists ^^

**Comment by jef** [comment]
Aha, very interesting. Well, it'll sure help out you and others!

Thanks for the support.

**Pull request merged**
