### PR TITLE
feat(store): add amd rx 6000 series model

### PR DESCRIPTION
**Pull request by rcbevans**
### Description
AMD RX 6800/6800XT/6900XT to Series type.  Extend .env-example with new MAX_PRICE config.  Add AMD reference and Strix LC as model types.  Add Sapphire as new brand.

### Testing

Verified program runs without error.  Tested that filtering series to new AMD series runs, albeit there are no product pages to check.

### CODE REVIEW

**Comment by frotofraggins** [comment]
was this added?

**Comment by kckaiwei** [comment]
No, and the models have yet to be updated.

**Comment by foxlet** [comment]
The URL for the regular RX 6800 (non-XT) is https://www.amd.com/en/direct-buy/5458373400/us by the way.

**Comment by jef** [comment]
Looks great! Thanks for also sorting lexicographically!

**Review by jef — DISMISSED** [review]

**Comment by jef** [comment]
Sorry about the linting. I need to make an update to the max columns. I don't like it being this short.

**Comment by tech-degenerate** [comment]
When will this be a feature we can get in a normal update? sorry sort of a noob...

**Review by jef — APPROVED** [review]

**Comment by jeff4uraree** [comment]
6900xt link:  https://www.amd.com/en/direct-buy/5458372200/us

**Pull request merged**
