### PR TITLE
chore(store): rx6800xt for memoryexpress, amazon-ca

### PR DESCRIPTION
**Pull request by StanZha**
few more urls added for gpu items at memoryexpress and amazon-ca

requested by @tempestbk

### CODE REVIEW

**Comment by StanZha** [comment]
@tempestbk test run below
Capture

**Comment by tempestbk** [comment]
Thank you

**Comment by tempestbk** [comment]
Thank you much appreciated

**Comment by jef** [comment]
Great! Thank you very much :)

**Review by jef — APPROVED** [review]

**Pull request merged**
