### PR TITLE
feat(store): add pcking and acompc

### PR DESCRIPTION
**Pull request by KnotenJoe**
Another store for Germany.  I tested the code on my pc.

### CODE REVIEW

**Review by jef — DISMISSED** [review]
Great! Thank you!

**Comment by jef** [comment]
Do you mind adding to the docs?

**Comment by jef** [comment]
I added the docs. You're gonna need to change `pcking` to `pcking.ts` and add it to the `index.ts`.

**Comment by KnotenJoe** [comment]
I think I did it? Sorry, I'm totally new to this and not sure. But if this checks out I also have another store for Germany that I could add.

**Comment by KnotenJoe** [comment]
I think I got it now.

**Comment by jef** [comment]
Looks great! Thank you very much. I can go in and fix the linting. This is great for a first time!

**Comment by KnotenJoe** [comment]
Thanks

**Review by jef — APPROVED** [review]

**Pull request merged**
