### PR TITLE
Update amazon-de.ts

### PR DESCRIPTION
**Pull request by KnotenJoe**
### Description

price checking was broken

### Testing
tested with different pricing

### CODE REVIEW

**Comment by Resaec** [comment]
I can not reproduce this container id on amazon.de pages. Can you provide a link to a page that uses this container?

**Comment by selop** [comment]
I've checked some items which are on sale and some which aren't is still see `#priceblock_ourprice` as the only tag.

**Comment by KnotenJoe** [comment]
I'm sorry. I was occupied over the holidays. I found the container id once for a 3080 model but it seems it was only a temporal change and was changed again. Sorry for wasting your time.

**Comment by jef** [comment]
No worries! Thanks for the report 😀

**Pull request closed without merging**
