### PR TITLE
chore(store): add rx6900xt for microcenter, newegg, bestbuy, amd

### PR DESCRIPTION
**Pull request by StanZha**
Added direct urls for rx 6900 xt gpu for following model classes
microcenter
newegg
bestbuy
amd official store

### CODE REVIEW

**Review by jef — APPROVED** [review]
Awesome! Thank you.

**Review by jef — APPROVED** [review]

**Comment by tempestbk** [comment]
Can we possible the Canadian stores as when looking for rx6900xt in Canadian stores program doesn't look for the card.

**Comment by StanZha** [comment]
@tempestbk can you provide Canadian store urls please?

**Comment by tempestbk** [comment]
Of course

NEWEGG Canada
https://www.newegg.ca/sapphire-radeon-rx-6900-xt-21308-01-20g/p/N82E16814202393
https://www.newegg.ca/asrock-radeon-rx-6900-xt-rx6900xt-16g/p/N82E16814930051
https://www.newegg.ca/gigabyte-radeon-rx-6900-xt-gv-r69xt-16gc-b/p/N82E16814932384
https://www.newegg.ca/msi-radeon-rx-6900-xt-rx-6900-xt-16g/p/N82E16814137618
https://www.newegg.ca/powercolor-radeon-rx-6900-xt-axrx-6900xt-16gbd6-m2dhc/p/N82E16814131774

AMD Canada
https://www.amd.com/en/direct-buy/5458372200/ca

I hope this is what is needed.

Also see the problem Newegg is the only Canadian retailer I was able to
find 6900xt listed on their site

**Pull request merged**
