### PR TITLE
fix(amazon-eu): checking price selector

### LINKED ISSUE #2813: [Bug]: Amazon-uk is ignoring MAX_PRICE_SERIES filter
### Expected Behavior

Streetmerchant should have ignored the amazon-uk items that were coming back with higher price tags than what was specified in the MAX_PRICE_SERIES filter.

### Current Behavior

Streetmerchant is instead accepting amazon-uk items that have a higher price tag than what is specified in the MAX_PRICE_SERIES filter.

### What operating system are you seeing the problem on?

Windows

### Relevant log output

```shell
n/a
```

### Configuration

```shell
# ** All configuration variables are optional **
# Copy this file and name it as `dotenv` (without backticks)
# Read https://jef.buzz/streetmerchant/getting-started/#customization for help on customizing this file
########################################################################################################
EMAIL_PASSWORD=Password
EMAIL_USERNAME=Email
LOW_BANDWIDTH=true
MAX_PRICE_SERIES_3070=500
MAX_PRICE_SERIES_3070TI=600
MAX_PRICE_SERIES_3080=700
SHOW_ONLY_SERIES=3070,3080,3070ti
STORES=amazon-uk,amd-uk,ao,argos,aria,awd,box,bt,ccl,corsair-uk,currys,ebuyer,game,johnlewis,novatech,overclockers,scan,shopto,smythstoys,very,nvidia-gb
SMTP_ADDRESS=smtp-mail.outlook.com
SMTP_PORT=587
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by MurrayGroves**
### Description

Fixes #2813 
Updated the store models for all the European Amazon stores. Previously the price container was `#priceblock_ourprice` which does not work, updated to `.a-text-price`, which does work. This not working meant that Amazon listings above the max price would not be filtered out.

### Testing
Ran streetmerchant with only European Amazon stores, for all products, with a low max_price. Verified that all stores rejected a listing due to high price.

### CODE REVIEW

**Review by jef — APPROVED** [review]
Thanks! Appreciate your help.

**Comment by J-Swift** [comment]
Heads up: this probably also applies to amazon US it looks like.

**Comment by J-Swift** [comment]
OK, I've confirmed this fixed an issue I was having with amazon US alerting even though max price was violated.

**Comment by hkennyv** [comment]
Seeing this issue as well with Amazon US currently with `streetmerchant@3.5.0`

**Comment by jef** [comment]
> Seeing this issue as well with Amazon US currently with `streetmerchant@3.5.0`

Do you mind creating a PR to update, @hkennyv or @J-Swift?

**Comment by 2phones** [comment]
> > Seeing this issue as well with Amazon US currently with `streetmerchant@3.5.0`
> 
> Do you mind creating a PR to update, @hkennyv or @J-Swift?

AmazonUS  

```
maxPrice: {
      container: '.a-offscreen',
    },
```

**Pull request merged**
