### PR TITLE
improvement(store): add ps5 accessories to most US retailers

### PR DESCRIPTION
**Pull request by chrisfkell**
### Description

Updated the existing sony store dualsense stock alert to follow common item patterns adapted to the dualsense controller. Added GameStop stock alert for the same device following the same pattern.

### Testing

Minor change tested with latest release on local instance of streetmerchant

### CODE REVIEW

**Comment by jef** [comment]
Is this necessary? Is the controller really low in stock? 😮

**Comment by chrisfkell** [comment]
It was low stock for a while. Not sure that it's really an issue now but noticed it was in the PS store file already so figured I'd implement it properly.

**Comment by dereckhall** [comment]
it's sort of a problem with all the ps5 accessories to be honest. scalpers are grabbing the dualsense charging dock, the media remote, pulse3d headphones, and selling for double/triple. they're quite hard to find in stock.

pulse3d: https://www.bestbuy.com/site/sony-playstation-pulse-3d-wireless-headset-compatible-for-both-playstation-4-playstation-5-white/6430164.p?skuId=6430164

media remote: https://www.bestbuy.com/site/sony-playstation-5-media-remote/6430167.p?skuId=6430167

dualsense charger: https://www.bestbuy.com/site/sony-playstation-5-dualsense-charging-station-white/6430165.p?skuId=6430165

i'd say if you're adding a single controller, you may as well knock out these other accessories.

i've never seen the controller go out of stock anywhere.

**Comment by chrisfkell** [comment]
Is this still something ya'll are interested in accepting. Can refactor if necessary.

**Comment by afst3r** [comment]
can we not manually add these if we get the url etc and add them to the site coding or is there other things we need to do as well

**Comment by jef** [comment]
Cool! This seems good. If we can resolve the conflicts, I wouldn't mind seeing this in.

**Comment by jef** [comment]
> can we not manually add these if we get the url etc and add them to the site coding or is there other things we need to do as well

https://jef.codes/streetmerchant/help/general/#adding-a-store

**Pull request closed without merging**
