### PR TITLE
fix(store): update out of stock detection for MediaMarkt and Saturn

### LINKED ISSUE #1545: False positives for mediamarkt.de and saturn.de
## Expected Behavior

Vendors do not have the card in stock. No notification or alert should occur.

## Current Behavior

Streetmerchant alerts about the item being in stock while it's actually not.
The problem has just recently started to occur. Like an hour ago. Before that it was working as expected.

## Steps to Reproduce

Example link: https://www.mediamarkt.de/de/product/-2681866.html

Run streetmerchant with one of those shops active. 
See screenshots attached 

success-1609248769113
success-1609248770197

### PR DESCRIPTION
**Pull request by X123Moin**
Fixes #1545

### CODE REVIEW

**Comment by neatchee** [comment]
+1

**Comment by fnk93** [comment]
@X123Moin Maybe don't overwrite the old tags, as MM and Saturn are changing these from time to time, but add the new tags to the list. As well as maybe add:
`{
    container: '#root',
    text: ['Dieser Artikel ist bald wieder für Sie verfügbar']
},`

**Comment by gigi2006** [comment]
> @X123Moin Maybe don't overwrite the old tags, as MM and Saturn are changing these from time to time, but add the new tags to the list. As well as maybe add:
> `{ container: '#root', text: ['Dieser Artikel ist bald wieder für Sie verfügbar'] },`

yes they have already changed 2 or 3 times back and forth today. really annoying.

**Review by theinternal — APPROVED** [review]
Implemented this in my own fork - works fine/no false positives anymore, thx!

**Review by jef — APPROVED** [review]
Makes sense to me. Thank you!

**Pull request merged**
