### PR TITLE
feat(store): add Norwegian stores

### PR DESCRIPTION
**Pull request by davols**
Added Elkjop.no, komplett.no, dustinhome.no, power.no and proshop.no norwegian shops. 
Komplett, Dustin (DustinHome) and Power also exists in Sweden, hence the No/.no suffix. 

### Description
Right now I've only been interested in 3080s so that's what I've added so far. They are all out of stock but 'IN STOCK' have been tested by other random products in each webshop. 

### Testing
Tested out of stock and in stock (in stock by using random other product link) for all new webshops. Tried to get maxprice to work but failed.

### CODE REVIEW

**Review by jef — DISMISSED** [review]
Great! Thank you!

**Comment by jef** [comment]
Do you mind adding the stores to the `docs/`?

**Comment by davols** [comment]
> Do you mind adding the stores to the `docs/`?

Just update filter.md with the new stores and environment variables or something more?

**Comment by jef** [comment]
> > Do you mind adding the stores to the `docs/`?
> 
> Just update filter.md with the new stores and environment variables or something more?

Nope! Good to go!

**Review by jef — APPROVED** [review]
Thank you! :relaxed:

**Pull request merged**
