### PR TITLE
feat: memoryexpress website support

### PR DESCRIPTION
**Pull request by omelettedufromagee**
### Description

Adding MemoryExpress website in Canada. Only track the online store
stock for now. Might add the stores stock later like microcenter.
Only track Ryzen 5000-series for now because RTX 3000-series is only
available in store backorder.

### Testing

- Tested with In Stock product using test:series

### CODE REVIEW

**Review by jef — DISMISSED** [review]
Looks good to me!

Thanks!

**Comment by jef** [comment]
Oh, actually. Do you mind adding this site to the README? Thanks!

**Comment by omelettedufromagee** [comment]
Added memoryexpress into the doc.
I'll work on canadacomputers next.
Thanks for the tool! It's awesome! Keep me busy while trying to get a 3080 and 3900X lol

**Comment by jef** [comment]
> Added memoryexpress into the doc.
> I'll work on canadacomputers next.
> Thanks for the tool! It's awesome! Keep me busy while trying to get a 3080 and 3900X lol

Thanks for contributing! Wouldn't be what it is now without you and everyone else!

**Review by jef — APPROVED** [review]

**Comment by omelettedufromagee** [comment]
Fun fact: memoryexpress opened backorder this morning at 11:31am, I was able to order by 11.32. That's awesome. Hopefully they will have stock soon!

**Comment by jef** [comment]
That's great news!

**Pull request merged**
