### PR TITLE
feat(nvidia): updated store for europe

### LINKED ISSUE #1393: Deprecate nvidia-api and update nvidia store
## Expected Behavior

We should be able to search for Founders Edition cards from the NVIDIA store for all officially supported countries, namely:

- France, Belgium and Luxembourg via LDLC
- Germany and Austria via NBB
- UK and Ireland via Scan
- Spain via LDLC

Ever since NVIDIA updated their store around 3 months ago, the Founders Edition are no longer sold by Nvidia themselves and they have opted to partner with some retailers in those respective countries to sell the FE cards instead. We should be able to capture FE card availability with the updated process.

This therefore makes `nvidia-api` obsolete and should now be deprecated.

## Current Behavior

- Must be able to scan for FE card availability for all RTX 3000 series products in the supported countries
- `nvidia-api` should be deprecated
- `nvidia` should be updated

## Steps to Reproduce

1. Try using the `nvidia` store to search for FE cards in the supported countries.
2. Notice that they don't work.

### PR DESCRIPTION
**Pull request by YiIdirim**
### Description

Fixes #1393 

- Check stock for all Founders Edition cards in the supported European countries.
- Removed `nvidia-api` as it is no longer updated.
- Updated `nvidia` with localised store variables, e.g. `nvidia-de`.

Note: When a card comes into stock, the partner site link is always randomised which means the link is always different every time there is a drop. This PR will notify you when the card comes into stock via the Nvidia store page as opposed to the partner site. This way the correct link is always found.

Please view the issue linked above for detailed information.

### Testing

- Performed robust testing with the new stores.
- Performed testing when old stores removed.
- Verified functionality works as expected.

### CODE REVIEW

**Comment by fmsimp** [comment]
Hi how can i update the streetmarchent? 
with this code?
####
git clone https://github.com/jef/streetmerchant.git
cd streetmerchant && npm i && npm run start
####

**Comment by jef** [comment]
Yeah, this nvidia-api definitely needed to go. I wasn't sure how other regions outside the US were working lately. I'll review this a little later today and hopefully get it in soon enough!

**Comment by kakashi84** [comment]
> Yeah, this nvidia-api definitely needed to go. I wasn't sure how other regions outside the US were working lately. I'll review this a little later today and hopefully get it in soon enough!

please inser when you can, nvidia-it

**Comment by sohaiiil** [comment]
> > Yeah, this nvidia-api definitely needed to go. I wasn't sure how other regions outside the US were working lately. I'll review this a little later today and hopefully get it in soon enough!
> 
> 
> 
> please inser when you can, nvidia-it

Sorry but Nvidia don't sell the Founders Edition cards in Italy. And I'm pretty sure none of the retailers in Germany or France ship to Italy either.

**Comment by kakashi84** [comment]
> > > Yeah, this nvidia-api definitely needed to go. I wasn't sure how other regions outside the US were working lately. I'll review this a little later today and hopefully get it in soon enough!
> > 
> > 
> > please inser when you can, nvidia-it
> 
> Sorry but Nvidia don't sell the Founders Edition cards in Italy. And I'm pretty sure none of the retailers in Germany or France ship to Italy either.

sorry but there nvidia sold 3070 3080 and 3090 on nvidia.it

**Comment by sohaiiil** [comment]
@kakashi84, I'm afraid you're mistaken. The nvidia store is only used to directly buy the Founders Edition. This PR is for Founders Edition cards only. I checked and verified that Nvidia do not directly sell the Founders Edition cards in Italy.

**Comment by kakashi84** [comment]
> @kakashi84, I'm afraid you're mistaken. The nvidia store is only used to directly buy the Founders Edition. This PR is for Founders Edition cards only. I checked and verified that Nvidia do not directly sell the Founders Edition cards in Italy.

you are right. but when launch the new generation there is a shop. i control now and the site go to nvidia.es

**Comment by jackevans211** [comment]
Hey, guys when do you think this will get added, i set it up myself from this info but what I updated it, there were issues so had to start again?

**Comment by YiIdirim** [comment]
@jef any update on this?

**Review by jef — APPROVED** [review]
Great! Thanks for doing this. This has been on my mind. Sorry for getting to this late.

I appreciate your help and your contribution! 🚀

**Comment by YiIdirim** [comment]
> Hey, guys when do you think this will get added, i set it up myself from this info but what I updated it, there were issues so had to start again?

It's been merged in. Should work now.

**Pull request merged**
