### PR TITLE
chore(store): add rx6900xt for newegg(-ca), amd-ca, bestbuy, and microcenter

### PR DESCRIPTION
**Pull request by StanZha**
added few new urls for Canada stores and few new items for USA

### CODE REVIEW

**Comment by StanZha** [comment]
@tempestbk
Capture

**Comment by tempestbk** [comment]
Sorry for being a noob, but can you tell me if 6800xt needs to be added as
well for Canadian stores?

**Comment by tempestbk** [comment]
Thank you!

**Review by jef — APPROVED** [review]
Awesome! Love to see it. Thank you! :rocket:

**Comment by StanZha** [comment]
@tempestbk it seems variety of 6800xt already added to newegg-ca:
https://github.com/jef/streetmerchant/blob/be1953b2069fce72969904c1bc18055df73f4b6b/src/store/model/newegg-ca.ts#L571
and single items in amd-ca:
https://github.com/jef/streetmerchant/blob/be1953b2069fce72969904c1bc18055df73f4b6b/src/store/model/amd-ca.ts#L31

**Comment by tempestbk** [comment]
Should I get the urls for 6800xt and send them like I did with the 6900x or
has someone already done so? Again sorry for being a noob.

**Comment by StanZha** [comment]
Amd Canada store has one link for 6800xt reference. Newegg Canada has 13 links. I believe you all covered.

**Comment by tempestbk** [comment]
I've found a bit more

Memory Express
https://www.memoryexpress.com/Products/MX00115124
https://www.memoryexpress.com/Products/MX00115048
https://www.memoryexpress.com/Products/MX00114996

Amazon Canada
https://www.amazon.ca/XFX-Speedster-DisplayPort-Graphics-RX-68XTACBD9/dp/B08NX14LV1/ref=sr_1_1?dchild=1&keywords=rx+6800xt&qid=1608043699&refinements=p_n_availability%3A12035748011&rnid=12035746011&s=electronics&sr=1-1
https://www.amazon.ca/Sapphire-Radeon-Express-Gaming-Graphics/dp/B08PQ585CX/ref=sr_1_2?dchild=1&keywords=rx+6800xt&qid=1608043699&refinements=p_n_availability%3A12035748011&rnid=12035746011&s=electronics&sr=1-2

Thank you for all your help!

>

**Pull request merged**
