### PR TITLE
chore(store): add more links to norwegian stores

### PR DESCRIPTION
**Pull request by WildCard1**
### Description

added more products to norwegian stores

### Testing

successfully ran it locally with npm run start

### CODE REVIEW

**Review by davols — DISMISSED** [review]

**Comment by WildCard1** [comment]
Any chance for merging this to main :) ?

**Review by jef — APPROVED** [review]
Sorry for the delay. Thank you for the additions!

**Comment by jef** [comment]
Do you mind running `npm run fix` to fix up the linting problems? After that, we can merge it in!

Thank you :)

**Comment by WildCard1** [comment]
Sorry, looking at it now :)

**Comment by WildCard1** [comment]
npm run fix returned:

`C:\Users\abc\github\streetmerchant>npm run fix

> streetmerchant@3.5.0 fix
> gts fix

version: 16

Oops! Something went wrong! :(

ESLint: 7.27.0

ESLint couldn't determine the plugin "node" uniquely.

- C:\Users\abc\github\streetmerchant\streetmerchant-non\streetmerchant\node_modules\eslint-plugin-node\lib\index.js (loaded in "streetmerchant-non\streetmerchant\.eslintrc.json » ./node_modules/gts/")
- C:\Users\abc\github\streetmerchant\node_modules\eslint-plugin-node\lib\index.js (loaded in ".eslintrc.json » ./node_modules/gts/")

Please remove the "plugins" setting from either config or remove either plugin installation.

If you still can't figure out the problem, please stop by https://eslint.org/chat/help to chat with the team.

Error: Command failed with exit code 2: node ./node_modules/eslint/bin/eslint --fix **/*.ts **/*.js **/*.tsx **/*.jsx --no-error-on-unmatched-pattern
    at makeError (C:\Users\abc\github\streetmerchant\node_modules\execa\lib\error.js:59:11)
    at handlePromise (C:\Users\abc\github\streetmerchant\node_modules\execa\index.js:114:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async run (C:\Users\abc\github\streetmerchant\node_modules\gts\build\src\cli.js:123:17) {
  shortMessage: 'Command failed with exit code 2: node ./node_modules/eslint/bin/eslint --fix **/*.ts **/*.js **/*.tsx **/*.jsx --no-error-on-unmatched-pattern',
  command: 'node ./node_modules/eslint/bin/eslint --fix **/*.ts **/*.js **/*.tsx **/*.jsx --no-error-on-unmatched-pattern',
  exitCode: 2,
  signal: undefined,
  signalDescription: undefined,
  stdout: undefined,
  stderr: undefined,
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}`

**Review by jef — APPROVED** [review]

**Comment by jef** [comment]
Thanks @WildCard1!

**Pull request merged**
