### PR TITLE
feat(store): support for kabum (amd and rtx 30 series)

### PR DESCRIPTION
**Pull request by HeitorLM**
### Description

Adds support for brazilian store Kabum (kabum.com.br).
AMD and RTX 30 Series.

### Testing

I tested using random in stock items as placeholder and it seems to work just fine.

### CODE REVIEW

**Comment by tempestbk** [comment]
Can someone make a request to add Canada Computers to the list of stores?

**Review by jef — APPROVED** [review]

**Review by jef — CHANGES_REQUESTED** [review]
Looks great! Do you mind adding to the README of the change?

Thanks!

**Comment by tempestbk** [comment]
I'm not sure how to do it

let me do some research.

this is completely new to me.



Best regards,

Dan Marmerstein
Director of Production Services
"Dolphies Promo Group Canada Inc."

SHOWROOM:
165 Dolomite Drive,
Toronto, ON, M3J 2N1, Canada
o: +1 (416) 840 0100
c: +1 (416) 822 9200
f: + 1 (416) 913 0125
e: dmarmer@dolphiespromo.com
w: www.DolphiesPromo.com
skype: tempestbk
viber: +14168229200
warehouses: ON, FL and NY
_______________________

**Comment by jef** [comment]
> I'm not sure how to do it let me do some research. this is completely new to me.

Sounds good! I can do it for you so we can get this in as well. You let me know.

**Comment by tempestbk** [comment]
If you could thank you.

What is the best way to support your project?

**Review by jef — APPROVED** [review]

**Pull request merged**
