### PR TITLE
feat: add support for 4080 and more 4090 stores

### PR DESCRIPTION
**Pull request by bobbydp**
(US - Amazon, Best Buy, Microcenter, PNY, Zotac)
Merge from limboed pull request by Mr-Tech-13 and used PR 3085 as a template

### Description
I cherry picked the salient Mr-Tech-13 modifications for the stores that I am able to visit and read (US Based Stores)

### Testing
running locally with a handful of the add to cart links on 4080 working. Admittedly I copied some of Mr-Tech-13s 4080 URLs wholesale trusting that those are genuine and work. 4090 links I was more particular about and pasting them into browser to ensure they are active.

### CODE REVIEW

**Comment by bobbydp** [comment]
I incorporated some clean up of redundant 4090 entries on B&H and Newegg as well from a past PR I closed.

**Review by jef — DISMISSED** [review]
Great! Thank you 🙇

**Review by jef — APPROVED** [review]
Just made some linting changes. Should be good now! Thanks again :)

**Comment by bobbydp** [comment]
FWIW, I got my 4090 2 weeks ago thanks to **you** and this wonderful tool!! Appreciate you greatly

**Comment by jef** [comment]
@bobbydp Thanks for adding these in and congrats on your new 4090!!! And thanks for letting me know, love hearing these stories :)

**Pull request merged**
